### ISSUE TITLE
Justificativas

### ISSUE THREAD

**Issue by Camilasanches07** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#11]

**Comment by AliceMiranda1** [comment]
A dependência excessiva de redes sociais é um problema de importância crescente na sociedade contemporânea, e há várias razões que motivam abordá-lo de forma proativa. Escolhemos este objetivo específico devido ao seu impacto significativo na saúde mental, no bem-estar emocional e no funcionamento social das pessoas. 

Para quantificar o problema, podemos recorrer a diversas fontes de dados e pesquisas. Segundo um estudo realizado pela Royal Society for Public Health (RSPH) do Reino Unido em 2017, as redes sociais, como Instagram, Snapchat, Facebook e Twitter, foram classificadas como as plataformas mais prejudiciais para a saúde mental dos jovens, contribuindo para a ansiedade, depressão, isolamento e baixa autoestima (RSPH, 2017).

Além disso, uma pesquisa conduzida pela Pew Research Center em 2018 revelou que 68% dos adultos americanos usam o Facebook, enquanto 73% dos adolescentes americanos têm acesso ao YouTube e 51% usam o Instagram. A mesma pesquisa destacou que 45% dos adolescentes entrevistados estão online "quase constantemente" (Pew Research Center, 2018).

Outro estudo importante é o realizado pela Universidade de Pittsburgh em 2016, que descobriu uma ligação entre o tempo gasto em redes sociais e a falta de sono entre jovens adultos, o que pode levar a uma série de problemas de saúde, incluindo obesidade, depressão e ansiedade (Primack et al., 2016).

Esses dados evidenciam a amplitude e a gravidade do problema da dependência de redes sociais e justificam plenamente a importância de abordá-lo de maneira eficaz. Através de questionários, entrevistas e análise de dados estatísticos, pretendemos entender melhor como as redes sociais afetam indivíduos em diferentes faixas etárias e contextos sociais, para desenvolver estratégias e intervenções eficazes para minimizar seus impactos negativos.

**Referências:**

- Royal Society for Public Health (RSPH). (2017). #StatusOfMind: Relatório da RSPH sobre a saúde da juventude social e plataformas de mensagens.
  
- Pew Research Center. (2018). Teens, Social Media & Technology 2018.

- Primack, B. A., Shensa, A., Sidani, J. E., Whaite, E. O., Lin, L. Y., Rosen, D., ... & Miller, E. (2016). Social media use and perceived social isolation among young adults in the U.S. American Journal of Preventive Medicine, 53(1), 1-8.
