### ISSUE TITLE
Objetivos de Desenvolvimento Sustentável

### ISSUE THREAD

**Issue by Marthaevang** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#15]
Os Objetivos de Desenvolvimento Sustentável (ODS) constituem uma plataforma global estabelecida pelas Nações Unidas, visando enfrentar os desafios socioeconômicos e ambientais até 2030. Esses objetivos são interligados e abrangem uma variedade de áreas, desde a erradicação da pobreza até a preservação do meio ambiente.

Este projeto visa conscientizar sobre os impactos da dependência excessiva de redes sociais em relação a três áreas-chave dos ODS: Saúde e Bem-Estar (ODS 3), Educação de Qualidade (ODS 4) e Trabalho Decente e Crescimento Econômico (ODS 8).

Saúde e Bem-Estar (ODS 3): O uso excessivo das redes sociais tem sido associado a problemas de saúde mental, como ansiedade, depressão e isolamento social. A busca incessante por validação online, comparação constante com os outros e exposição a conteúdos prejudiciais podem afetar negativamente o bem-estar das pessoas. Portanto, promover o equilíbrio no uso das redes sociais e conscientizar sobre seus impactos na saúde mental é fundamental para alcançar esse objetivo.

Educação de Qualidade (ODS 4): O uso descontrolado das redes sociais pode interferir no processo de aprendizagem e na qualidade da educação. O tempo gasto em frente às telas pode prejudicar a concentração, reduzir a capacidade de retenção de informações e até mesmo interferir nas habilidades sociais e cognitivas das crianças e jovens. Portanto, é importante promover a alfabetização digital responsável e garantir que as escolas abordem os aspectos positivos e negativos das redes sociais em seus currículos.

Trabalho Decente e Crescimento Econômico (ODS 8): A dependência excessiva das redes sociais pode impactar negativamente a produtividade dos trabalhadores, reduzindo o tempo e a atenção dedicados às suas tarefas laborais. Isso pode resultar em desempenho inferior no trabalho e, consequentemente, em uma redução da eficiência e do crescimento econômico. Além disso, para as empresas, a dependência excessiva das redes sociais entre os funcionários pode levar a uma diminuição da eficiência e da competitividade. Isso pode afetar negativamente o crescimento econômico, especialmente em setores nos quais a produtividade e a inovação são essenciais para o sucesso empresarial.

Em suma, a dependência excessiva de redes sociais pode impactar negativamente vários aspectos da vida das pessoas, incluindo saúde, educação e emprego. Portanto, integrar estratégias para lidar com esse desafio dentro dos esforços para alcançar os Objetivos de Desenvolvimento Sustentável é essencial para garantir um futuro mais equitativo e sustentável para todos.

**Comment by Camilasanches07** [comment]
Tópico 3, 4 e 8
