### ISSUE TITLE
Slide

### ISSUE THREAD

**Issue by AliceMiranda1** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#22]
O documento "Dependência Excessiva de Redes Sociais" descreve a dependência nesse contexto como um uso compulsivo e descontrolado das plataformas online, comparável à dependência química devido à ativação da dopamina no cérebro. Essa condição pode gerar efeitos positivos, como acesso à informação e conexão social, mas também negativos, como isolamento social e redução da produtividade. Para lidar com esses desafios, o material destaca aplicativos de gerenciamento de tempo, como o Freedom, Forest e Screen Time, como recursos úteis. Enfatiza-se a importância da conscientização sobre os impactos negativos e da busca por equilíbrio entre as atividades online e offline para preservar a saúde mental e promover uma cultura digital responsável.

**Comment by AliceMiranda1** [comment]
Montagem do site
- Como foi o passo a passo da montagem do slide
- como foi feito

**Comment by Marthaevang** [comment]
A dependência excessiva de redes sociais refere-se ao uso compulsivo e descontrolado dessas plataformas online, que funciona de forma similar à dependência química, ativando a produção de dopamina no cérebro. Esse vício pode trazer tanto aspectos positivos, como o acesso à informação, compartilhamento de conhecimento e conexão social, quanto aspectos negativos, como isolamento social, distração e produtividade reduzida, além de potenciais problemas na saúde mental.

No material, também foram citados possíveis aplicativos de gerenciamento de tempo, como o Freedom, que bloqueia sites e aplicativos por um tempo definido, incentivando o usuário a focar em tarefas importantes e evitar distrações online; o Forest, onde usuários plantam uma semente virtual que cresce sem uso do dispositivo, incentivando a concentração; e o Screen Time, que controla e registra o tempo gasto em aplicativos no iOS.

Por fim, o material enfatiza que é essencial conscientizar sobre os impactos negativos da dependência de redes sociais e promover o equilíbrio entre a vida online e offline para proteger a saúde mental e fomentar uma cultura digital responsável.
