### ISSUE TITLE
Mentimete (Site de perguntas)

### ISSUE THREAD

**Issue by AliceMiranda1** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#23]

**Comment by AliceMiranda1** [comment]
- Como criamos as perguntas?
- Como é nossos questionário?

**Comment by octavioRezende** [comment]
As perguntas são:

- Qual aplicativo você mais utiliza?
- Quanto tempo você passa no celular?
- Qual parte do dia você mais usa seu celular?
- Você acredita que o uso das redes sociais afeta sua autoestima de alguma forma?
- Por qual motivo vocês mais usam as redes sociais?
