### ISSUE TITLE
Dificuldades enfrentadas

### ISSUE THREAD

**Issue by Camilasanches07** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#24]
Nós enfrentamos algumas dificuldades com nosso projeto, como por exemplo:

**Comunicação Eficaz**: Precisamos simplificar os conteúdos acadêmicos que aprendemos na faculdade para que sejam acessíveis e interessantes para alunos mais jovens, para que eles consigam entender de maneira simples.

**Organização de Tarefas:** Distribuir funções entre os membros do nosso grupo foi uma dificuldade que enfrentamos.

**Timidez ao Apresentar**: A ansiedade de falar em público é uma dificuldade que muitos de nós enfrentamos. Mesmo estando bem preparados, a pressão de falar diante dos alunos afetou um pouco nosso desempenho.

**Comment by AliceMiranda1** [comment]
Quais foram as principais dificuldades enfrentadas pelo grupo?
