### ISSUE TITLE
Mudanças

### ISSUE THREAD

**Issue by Camilasanches07** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#25]

**Comment by AliceMiranda1** [comment]
Que mudanças poderiam ser realizadas que tornaria o processo mais eficiente?

**Comment by davizanatta7** [comment]
Mudanças que poderiam beneficiar e/ou então tornar mais eficiente o processo estão entre:

**Divisão de tarefas:** Nosso grupo sofreu com a divisão de tarefas de forma igualitária e que facilitasse o andamento do projeto. Dessa forma, poderíamos ter feito um compartilhamento melhor dos afazeres pra cada integrante e assim, além de mais eficiente, promoveria a evolução rápida e fluída do processo.

**Preparação para a apresentação:** De maneira geral, nosso grupo é feito de integrantes que sofrem com a timidez. Sendo assim, poderíamos ter divido falas e roteirizado a apresentação pra que assim ficasse à uma maneira suave de se apresentar para todos e que ajudasse a luta com nossa timidez.

**Otimização do conteúdo:** A priori, foi dificil simplificar os conteúdos e matérias vistas na faculdade para mostrar aos alunos mais novos. Dessa maneira, poderíamos ter feitos conversas para que todos pudessem dar ideia para maneiras que otimizassem o conteúdo e ficasse simples para que qualquer um, mas principalmente o publico alvo (alunos da escola), pudessem ter clareza sobre o que citaríamos ao decorrer de nossa conversa.
