### ISSUE TITLE
O que achamos?

### ISSUE THREAD

**Issue by Camilasanches07** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#26]
Tivems sucesso na apresentação do projeto, acredito que alcançamos o objetivo inicial, a nossa maior dificuldade havia sido entender o nosso público e encontrar uma maneira eficaz de conscientizá-los. No entanto ao analisar as estatísticas do Kahoot, percebemos que mesmo na faixa etária dos alunos, sendo adolescentes gostando de utilizar e interagir nas redes, os mesmos expressam o interesse em realizar diversos programas e não ficar somente na utilização de dispositivos móveis.

Durante a apresentação, houve uma alta participação da turma, com eles adicionando comentários em relação aos tópicos e fazendo algumas perguntas. Alguns deles também respondiam as perguntas apresentadas em voz alta. Entre os alunos tiveram alguns dispostos a compartilhar histórias pessoais, um aluno comentou "Quando eu tinha uns 12 anos passava mais tempo nas telas, as vezes pegava de 21:00 horas da noite e ficava até 7:00 da manhã", no momento em que perguntamos se eles já haviam verificado alguma vez o tempo de uso do celular um aluno relatou "Uma vez meu celular registrou 15 horas e isso só do celular, fora o tempo que fiquei no computador". Percebemos que eles seguiram bem as dinâmicas feitas ao decorrer dos slides , foram participativos no kahoot ,  e isso fez com que a apresentação fluísse melhor e ficasse mais leve e descontraída.

Com essa interação, ficou evidente que, embora os adolescentes estejam muito envolvidos com as redes sociais, muitos deles também reconhecem os impactos negativos do uso excessivo e mostram interesse em buscar um equilíbrio.

Queríamos conscientizá-los de que ao reduzir o tempo gasto nas telas, eles podem experimentar uma melhora significativa na qualidade de vida. Isso inclui aumentar o tempo disponível para outras atividades importantes como estudos, exercícios físicos e interações sociais presenciais. Acredito que conseguimos transmitir essa mensagem com clareza e que o objetivo que tínhamos com este projeto foi plenamente absorvido pelos alunos.

**Comment by AliceMiranda1** [comment]
O que nós do grupo achamos a respeito?
