### ISSUE TITLE
Interação com alunos

### ISSUE THREAD

**Issue by Camilasanches07** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#27]

**Comment by Camilasanches07** [comment]
Como foi a interação dos alunos com a gente?

(Fotos tiradas la)

**Comment by Luizoctav** [comment]
Os alunos interagiram bastante, compartilharam situações em que o excesso de redes sociais os atrapalhava e responderam a todas as perguntas que fizemos. Eles também não tiveram receio de fazer perguntas
