### ISSUE TITLE
Artefatos da Sprint 1 (Detalhamento do projeto)

### ISSUE THREAD

**Issue by Camilasanches07** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-1-ment2-manha-fbi_aplicativosonlines#5]
Pesquisa mostra que brasileiros passam 9h por dia ao celular ou em outros aparelhos eletrônicos 

 O uso excessivo de dispositivos eletrônicos, especialmente celulares, tornou-se uma preocupação global. Segundo dados do G1, os brasileiros passam em média nove horas e meia por dia utilizando dispositivos eletrônicos, o que levanta preocupações sobre os efeitos desse comportamento na vida cotidiana. Comparativamente, o tempo gasto nas redes sociais é substancialmente maior do que em outras nações, como o Japão, mesmo sendo este último líder em tecnologia.  

No Brasil, em particular, os dados são alarmantes, com os brasileiros liderando o ranking de tempo conectado às telas. Este projeto visa investigar os efeitos negativos desse comportamento sobre a saúde mental e o bem-estar dos brasileiros, além de propor estratégias para mitigar esse impacto e promover uma relação mais saudável com a tecnologia.  

De acordo com estudos citados pelo Jornal USP, o uso excessivo das redes sociais está associado a uma série de problemas de saúde mental, incluindo ansiedade e depressão. Além disso, há uma crescente preocupação com a intoxicação social, manifestada por sentimentos de exclusão, desestímulos e comparações incessantes, que podem levar à diminuição das interações offline e à queda da autoestima. 

O que podem causar a nossa saúde? 

Pesquisas demonstram que o uso intensivo das redes sociais pode resultar em uma série de problemas de saúde, desde ansiedade e depressão até preocupações com a autoestima e insatisfação com a aparência física. A professora Valéria Barbieri (professora da FFCLRP). destaca que a tendência à comparação constante alimentada pelas redes sociais pode levar a sentimentos de inveja, inferioridade e exclusão.  

Portanto, para combater esse problema, é crucial adotar medidas que promovam uma relação mais equilibrada com a tecnologia. Sugere-se desabilitar notificações das redes sociais, controlar o tempo de tela de aplicativos e priorizar atividades offline que promovam interações sociais reais. Estas medidas visam reduzir a procrastinação e promover um uso mais consciente e saudável dos dispositivos eletrônicos. 

Uso de aplicativos e ferramentas que visibilizam na melhora da organização para uma boa rotina: 

Forest: O Forest é um aplicativo que ajuda a controlar o tempo gasto no celular, incentivando o foco e a concentração. Você planta uma semente virtual e ela cresce enquanto você não utiliza o celular. Se você sair do aplicativo para acessar outras funções do dispositivo, a árvore morre. É uma maneira divertida de manter o foco e evitar distrações. 

Moment: O Moment é um aplicativo que rastreia quanto tempo você passa no seu dispositivo e em aplicativos específicos. Ele fornece relatórios detalhados sobre seus hábitos de uso, permitindo que você defina metas e limite o tempo gasto em dispositivos eletrônicos. 

Screen Time (Tempo de Uso): Esta é uma ferramenta integrada nos dispositivos iOS (iPhone e iPad) que permite monitorar e controlar o tempo gasto em aplicativos e categorias de aplicativos. Você pode definir limites de tempo para aplicativos específicos e receber relatórios semanais sobre seu uso. 

Digital Wellbeing (Bem-estar Digital): Similar ao Screen Time, o Digital Wellbeing é uma ferramenta incorporada aos dispositivos Android que ajuda a controlar o tempo gasto em aplicativos, estabelecer limites de uso e até mesmo pausar notificações para reduzir distrações. 

Freedom: O Freedom é um aplicativo que bloqueia sites e aplicativos específicos por um período determinado. Ele permite que você se concentre em tarefas importantes, evitando distrações online. 

StayFocusd: Uma extensão para navegadores de internet como o Google Chrome que permite bloquear sites específicos ou definir limites de tempo para o uso de determinados sites. É útil para evitar procrastinação online.

**Comment by AliceMiranda1** [comment]
Detalhamento do projeto
- explicar de forma mais profunda sobre nosso projeto
- O que vamos fazer/apresentar
- Explicar o nosso conograma
